[package]
edition = "2018"
name = "pektin"
version = "0.1.0"

[dependencies]
dotenv = "0.15"
redis = "0.21"
pretty-hex = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
trust-dns-proto = { version = "0.20", features = ["dnssec"] }

[lib]
name = "pektin"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "redis"
path = "src/redis.rs"