[package]
edition = "2018"
name = "pektin"
version = "0.1.0"

[dependencies]
dotenv = "0.15"
redis = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
trust-dns-proto = { git = "https://github.com/bluejekyll/trust-dns", branch = "main", features = ["dnssec", "serde-config"] }
url = { version = "2.1.0", features = ["serde"] }

[lib]
name = "pektin"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "json_test"
path = "src/json_test.rs"