version: "3.7"
services:
    pektin:
        build:
            context: "."
        restart: always
        environment:
            REDIS_URI: $REDIS_URI
            BIND_ADDRESS: $BIND_ADDRESS
            BIND_PORT: $BIND_PORT
        ports:
            - "127.0.0.1:53:$BIND_PORT/udp"
        networks:
            - pektin
    #redis:
    #    image: redis:alpine
    #    restart: always
networks:
    pektin:
        name: pektin-ui_default
